# Generated by Django 4.2.5 on 2023-10-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_kino'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
